spring.application.name=OrderStack

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Set max file size for single file upload (e.g., 100MB)
spring.servlet.multipart.max-file-size=100MB
# Set max request size for total upload (e.g., multiple files in a single request)
spring.servlet.multipart.max-request-size=100MB

# Disable Spring AI OpenAI auto-configuration
spring.ai.openai.enabled=false
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-ada-002

spring.ai.openai.api-key=dummy-key-to-bypass-startup-crash

# --- FEATURE TOGGLES ---
# Set to true to enable OpenAI embeddings, false to bypass them
app.feature.ai-enabled=false

# Add your insert-data script to the locations list, separated by a comma
spring.sql.init.schema-locations=classpath:init/schema.sql
spring.main.allow-bean-definition-overriding=true
spring.ai.vectorstore.pgvector.initialize-schema=false

# MUST BE FALSE FOR RENDER
spring.docker.compose.enabled=false

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true